import torch
a = torch.tensor([10,20,30])
b = torch.tensor([2,4,5])
print(a+b)
print(a-b)
print(a*b)
print(b/a)
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[2,0],[1,2]])
print(A.matmul(B))
x=torch.arange(1,17)
mat=x.reshape(4,4)
print(mat)
print(mat.T)